### ISSUE TITLE
Open resource on NWB explorer

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#65]
When clicking on a resource in the drawer, if the resource is a nwb file, that resource must be loaded inside the NWB Explorer application inside the frame.

Can use a parent to iframe message as already implemented in NWB explorer, with the new capability of loading a new file after the first load (see ...).

The last opened resource should also change accordingly in the workspace.

Related: the notebook associated to that same resource in nwb explorer should be part of the workspace and never change from one session to the other. So the working directory of nwb explorer must also change to be the workspace root. Note that the notebook created in such way is inside the workspace but it's not a resource. That's something to discuss.

- [x] Change the functionality in NWB explorer to load new files also after the first load by iframe message
- [ ] Change the working directory of NWB explorer to be the workspace folder (configurable)
- [ ] Add option to NWB explorer to use the same notebook for the same resource path
- [x] Send message from the frontend to the application with resource relative path to the workspace
- [x] Implement the update of last resource in the workspace manager

**Comment by zsinnema** [comment]
workspace manager already has the "open" rest api for a workspace resource. this call updates the last opened resource of the workspace record so next time we know what resource to open if a workspace is opened (it's a property of the workspace objects) :-)

**Comment by zsinnema** [comment]
@filippomc do you mean "if the type of the resource is NWB Explorer" then the resource will be opened by NWB Explorer.
right?
